apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: jenkins-selfsigned
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
spec:
  dnsNames:
    - jenkins.greengold.id
  secretName: selfsigned-cert-tls
  issuerRef:
    name: jenkins-selfsigned